language: c

#######################################################################################


os:
  - linux


#######################################################################################


before_install:

  # - sudo apt-get update -qq
  
  # downloading the best version of the linaro toolchain. 
  - git clone https://bitbucket.org/UBERTC/arm-eabi-4.9.git
  - export PATH=$PATH:$PWDarm-eabi-4.9/bin/
  
  - sudo apt-get install bc
  - sudo apt-get install libmpc-dev
  - sudo ln -s /opt/pkg/mpc1.0.1/lib/libmpc.so.3.0.0 /opt/pkg/mpc1.0.1/lib/libmpc.so.3


#######################################################################################


before_script:

  - export DST_PROJECT=$PWD
  # download and extract the linux source code.


#######################################################################################


script:
  - export KBUILD_BUILD_USER=assusdan
  - export KBUILD_BUILD_HOST=SRT
  - export ARCH=arm 
  - export CROSS_COMPILE=$PWD/arm-eabi-4.9/bin/arm-eabi-
  
  - make zetsubou_peach_defconfig
  - make zImage-dtb -j5
  
  - curl --upload-file errors.log https://transfer.sh/errors.log
  - curl --upload-file builds.log https://transfer.sh/builds.log  
  - curl --upload-file arch/arm/boot/zImage-dtb https://transfer.sh/zImage-dtb
