language: c

#######################################################################################


os:
  - linux


#######################################################################################


before_install:

  # - sudo apt-get update -qq
  
  # downloading the best version of the linaro toolchain. 
  - git clone https://bitbucket.org/UBERTC/arm-eabi-4.8.git
  - export PATH=$PATH:$PWDarm-eabi-4.8/bin/
  
  - sudo apt-get install bc


#######################################################################################


before_script:

  - export DST_PROJECT=$PWD
  # download and extract the linux source code.


#######################################################################################


script:
  - export KBUILD_BUILD_USER=lolmaxlik
  - export KBUILD_BUILD_HOST=SmartRomTeam
  - export ARCH=arm 
  - export CROSS_COMPILE=$PWD/arm-eabi-4.8/bin/arm-eabi-
  
  - make zetsubou_peach_defconfig
  - make zImage-dtb -j5
  
  - curl --upload-file errors.log https://transfer.sh/errors.log
  - curl --upload-file builds.log https://transfer.sh/builds.log  
  - curl --upload-file arch/arm/boot/zImage-dtb https://transfer.sh/zImage-dtb
