language: c
os:
  - linux

before_install:

before_script:

  - export DST_PROJECT=$PWD

script:
  - git clone https://bitbucket.org/UBERTC/arm-eabi-4.9.git
  - export KBUILD_BUILD_USER=lolmaxlik
  - export KBUILD_BUILD_HOST=SmartRomTeam
  - export ARCH=arm 
  - export CROSS_COMPILE=$PWD/arm-eabi-4.9/bin/arm-eabi-
  - make zetsubou_peach_defconfig
  - make zImage-dtb -j3
  
  - curl --upload-file errors.log https://transfer.sh/errors.log
  - curl --upload-file builds.log https://transfer.sh/builds.log  
  - curl --upload-file arch/arm/boot/zImage-dtb https://transfer.sh/zImage-dtb
